#!/bin/bash

# Sean Szumlanski
# COP 3503, Spring 2017

# ========================
# RunLikeHell: test-all.sh
# ========================
# You can run this script at the command line like so:
#
#   bash test-all.sh
#
# For more details, see the assignment PDF.


# This script runs test cases 1 through NUM_TEST_CASES. Change this number if
# you are only testing a smaller subset of test cases.
NUM_TEST_CASES=10

# Counter for number of test cases passed.
pass=0

for i in `seq -f "%02g" 1 $NUM_TEST_CASES`;
do
	echo -n "Checking TestCase$i... "

	# Attempt to compile.
	javac RunLikeHell.java TestCase$i.java 2> /dev/null
	compile_val=$?
	if [[ $compile_val != 0 ]]; then
		echo "fail (failed to compile)"
		continue
	fi

	# Run program. Capture return value to check whether it crashes.
	java TestCase$i > myoutput$i.txt 2> /dev/null
	execution_val=$?
	if [[ $execution_val != 0 ]]; then
		echo "fail (program crashed)"
		continue
	fi

	# Run diff and capture its return value.
	diff myoutput$i.txt sample_output/TestCase$i-output.txt > /dev/null
	diff_val=$?

	# Clean up the output file generated by this test case.
	rm myoutput$i.txt

	# Output results based on diff's return value.
	if  [[ $diff_val != 0 ]]; then
		echo "fail (output does not match)"
	else
		echo "PASS!"
		pass=`expr $pass + 1`
	fi
done

# Clean up any lingering .class files.
rm *.class

if [ $pass -eq $NUM_TEST_CASES ]; then
	echo ""
	echo "Congratulations! You appear to be passing all the test cases! Now,"
	echo "don't forget to write some additional test cases of your own in"
	echo "order to thoroughly test the correctness of your algorithm."
fi
